# Generated by Django 3.1.14 on 2022-05-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmelatracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogs',
            name='tes_t',
            field=models.TextField(default='None'),
        ),
    ]
