# Generated by Django 3.1.14 on 2022-05-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmelatracker', '0002_worklogs_tes_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogs',
            name='test_2',
            field=models.TextField(default='None'),
        ),
    ]
